spring:
  datasource:
    url: jdbc:h2:file:./h2db/vegitable
    driverClassName: org.h2.Driver
    username: sa
    password: pass
    
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      # default path: h2-console
      path: /h2-ui