### getAll()
GET http://localhost:8080/vegitable/list

### getAll(name)
GET http://localhost:8080/vegitable/list?name=パプリカ

### getById(id)
GET http://localhost:8080/vegitable/1

### create(vegitable)
POST http://localhost:8080/vegitable/
content-type: application/json

{
  "name": "赤パプリカ",
  "color": "赤",
  "price": "100"
}

### update(id, vegitable)
PUT http://localhost:8080/vegitable/1
content-type: application/json

{
  "name": "赤パプリカ",
  "color": "赤",
  "price": "777"
}

### delete(id)
DELETE http://localhost:8080/vegitable/1

### deleteAll()
DELETE http://localhost:8080/vegitable/

### findByColor(color)
GET http://localhost:8080/vegitable/?color=赤