### getAllVegitables()
GET http://localhost:8080/vegitable/list

### getAllVegitables(name)
GET http://localhost:8080/vegitable/list?name=パプリカ

### getVegitableById(id)
GET http://localhost:8080/vegitable/1

### createVegitable(vegitable)
POST http://localhost:8080/vegitable/
content-type: application/json

{
  "name": "赤パプリカ",
  "color": "赤",
  "price": "100"
}

### updateVegitable(id, vegitable)
PUT http://localhost:8080/vegitable/1
content-type: application/json

{
  "name": "赤パプリカ",
  "color": "赤",
  "price": "777"
}

### deleteVegitable(id)
DELETE http://localhost:8080/vegitable/1

### deleteAllVegitables()
DELETE http://localhost:8080/vegitable/

### findByColor(color)
GET http://localhost:8080/vegitable/?color=赤